const $ = id => document.getElementById(id);
let subjects = {}, currentSubject = '', page = 1, pageSize = 50, total = 0, subjectTotal = 0, currentItems = [];
function token(){return $('token').value.trim() || localStorage.getItem('adminToken') || ''}
function headers(){const h={'content-type':'application/json'}; if(token()) h.authorization='Bearer '+token(); return h}
async function api(url, opts={}){const res=await fetch(url,{...opts,headers:{...headers(),...(opts.headers||{})}});const data=await res.json();if(!res.ok||data.ok===false)throw new Error(data.error||'请求失败');return data}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function init(){const saved=localStorage.getItem('adminToken');if(saved)$('token').value=saved;$('token').onchange=()=>localStorage.setItem('adminToken',$('token').value.trim());const bank=await api('/api/subjects');subjects=bank.subjects||{};const keys=Object.keys(subjects);currentSubject=keys[0]||'';$('subjectSelect').innerHTML=keys.map(k=>`<option value="${esc(k)}">${esc(subjects[k].name)}（${subjects[k].question_count||0}）</option>`).join('');$('subjectSelect').value=currentSubject;$('subjectSelect').onchange=()=>{currentSubject=$('subjectSelect').value;page=1;loadList()};bind();loadList()}
function bind(){$('searchBtn').onclick=()=>{page=1;loadList()};$('keyword').onkeydown=e=>{if(e.key==='Enter'){page=1;loadList()}};$('typeFilter').onchange=()=>{page=1;loadList()};$('statusFilter').onchange=()=>{page=1;loadList()};$('prevBtn').onclick=()=>{if(page>1){page--;loadList()}};$('nextBtn').onclick=()=>{if(page*pageSize<total){page++;loadList()}};$('newBtn').onclick=()=>openEditor();$('closeBtn').onclick=closeEditor;$('backupBtn').onclick=backup;$('form').onsubmit=saveQuestion;$('copyJsonBtn').onclick=copyJson;['type','review_status','official_exam_part','chapter','difficulty','source_name','stem','options','answer','explanation','source_url','license_note'].forEach(id=>$(id).oninput=renderPreview)}
async function loadList(){const q=new URLSearchParams({page,pageSize,q:$('keyword').value.trim(),type:$('typeFilter').value,status:$('statusFilter').value});const data=await api(`/api/subjects/${currentSubject}/questions?${q}`);currentItems=data.questions||[];total=data.total||0;subjectTotal=subjects[currentSubject]?.question_count||total;renderList();$('title').textContent=(subjects[currentSubject]?.name||currentSubject)+'｜题库管理';$('statTotal').textContent=total;$('statSubject').textContent=subjectTotal;$('statPage').textContent=page;$('statSize').textContent=pageSize}
function renderList(){if(!currentItems.length){$('list').innerHTML='<div class="qitem">暂无题目。</div>';return}$('list').innerHTML=currentItems.map(q=>`<article class="qitem"><div class="qitem-head"><div><h3>${esc(q.stem)}</h3><div class="meta">${esc(q.chapter||'未分类')}｜${esc(q.official_exam_part||'未标注')}｜${esc(q.difficulty||'普通')}｜答案：${esc(Array.isArray(q.answer)?q.answer.join('、'):q.answer)}</div></div><span class="tag">${esc(q.type)} · ${esc(q.review_status||'')}</span></div><div class="meta">${(q.options||[]).map((o,i)=>String.fromCharCode(65+i)+'. '+esc(o)).join('　')}</div><div class="qactions"><button class="btn secondary" onclick="editQ('${esc(q.id)}')">编辑</button><button class="btn green" onclick="quickStatus('${esc(q.id)}','approved')">通过</button><button class="btn secondary" onclick="quickStatus('${esc(q.id)}','draft')">草稿</button><button class="btn red" onclick="delQ('${esc(q.id)}')">删除</button></div></article>`).join('')}
function getQ(id){return currentItems.find(q=>q.id===id)}
window.editQ=id=>openEditor(getQ(id));
function openEditor(q={}){ $('drawer').classList.add('show');$('editorTitle').textContent=q.id?'编辑题目':'新增题目';$('qid').value=q.id||'';$('type').value=q.type||'单选';$('review_status').value=q.review_status||'approved';$('official_exam_part').value=q.official_exam_part||'';$('chapter').value=q.chapter||'';$('difficulty').value=q.difficulty||'普通';$('source_name').value=q.source_name||'后台录入';$('stem').value=q.stem||'';$('options').value=(q.options||[]).join('\n');$('answer').value=Array.isArray(q.answer)?q.answer.join(','):q.answer||'';$('explanation').value=q.explanation||'';$('source_url').value=q.source_url||'';$('license_note').value=q.license_note||'';renderPreview()}
function closeEditor(){ $('drawer').classList.remove('show') }
function formData(){let ans=$('answer').value.trim();if($('type').value==='多选')ans=ans.split(/[、,，\s]+/).filter(Boolean).sort();return{type:$('type').value,review_status:$('review_status').value,official_exam_part:$('official_exam_part').value.trim(),chapter:$('chapter').value.trim(),difficulty:$('difficulty').value,source_name:$('source_name').value.trim()||'后台录入',stem:$('stem').value.trim(),options:$('options').value.split('\n').map(s=>s.trim()).filter(Boolean),answer:ans,explanation:$('explanation').value.trim(),source_url:$('source_url').value.trim(),license:'custom',license_note:$('license_note').value.trim()}}
function renderPreview(){ $('jsonPreview').textContent=JSON.stringify(formData(),null,2) }
async function saveQuestion(e){e.preventDefault();const id=$('qid').value;const body=JSON.stringify(formData());if(id)await api(`/api/subjects/${currentSubject}/questions/${encodeURIComponent(id)}`,{method:'PUT',body});else await api(`/api/subjects/${currentSubject}/questions`,{method:'POST',body});toast('已保存');closeEditor();await loadList()}
window.quickStatus=async(id,status)=>{const q=getQ(id);await api(`/api/subjects/${currentSubject}/questions/${encodeURIComponent(id)}`,{method:'PUT',body:JSON.stringify({...q,review_status:status})});toast('状态已更新');loadList()}
window.delQ=async(id)=>{if(!confirm('确定删除这道题？'))return;await api(`/api/subjects/${currentSubject}/questions/${encodeURIComponent(id)}`,{method:'DELETE'});toast('已删除');loadList()}
async function backup(){const data=await api('/api/admin/backup',{method:'POST',body:'{}'});toast('已备份');alert('备份目录：\n'+data.backup)}
async function copyJson(){await navigator.clipboard.writeText(JSON.stringify(formData(),null,2));toast('JSON已复制')}
init().catch(e=>{console.error(e);toast(e.message);$('list').innerHTML='<div class="qitem">加载失败：'+esc(e.message)+'</div>'});
